### ISSUE TITLE
[BUG] Attraction codes with letters instead of just numbers cause the container to crash

### ISSUE THREAD

**Issue by michivonah** [michivonah/europapark-alerts#1]
Used docker command: `docker run -d --name ep-alerts-test --env NOTIFICATION_TYPE=ntfy --env NTFY_URL="https://ntfy.example.com/topic" --env NTFY_ACCESS_TOKEN=<REDACTED> --env THEMEPARK=efteling --env SUBS=6261726f6e31383938,6465766c696567656e6465686f6c6c616e646572,64657a65737a77616e656e726f6e647661617274,64696f72616d61,646f756465747566666572,64726f6f6d766c75636874,666162756c61 michivonah/ep-alerts`

Container output:
```
root@server:/app# docker logs ep-alerts-test 
Themepark Wait Time Alerts
By Michi von Ah
Big thanks to the wartezeiten.app API!
Traceback (most recent call last):
  File "/app/main.py", line 73, in <module>
    checkTimes(subscribedAttractions, themepark)
  File "/app/main.py", line 53, in checkTimes
    if attraction["code"] in subscribedAttractions:
       ~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

Caused by the letters in the code of the attractions. Code has to be adjusted to support attraction codes with letters. (For parks like efteling)

**Comment by michivonah** [comment]
Fixed in the latest version. The container no longer stops, when he receives an invalid response from the API.
![Screenshot_20241013_124924](https://github.com/user-attachments/assets/bb9b5faf-63a6-498c-840b-a27d0aa8009e)
The container now shows a message in docker logs, when it received an invalid response. The affected attraction will be skipped for this time.
